name: Deploy

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.ssh_key }}

      - name: Deploy to server
        env:
          SSH_PORT: ${{ env.ssh_port }}
          SSH_USER: ${{ env.ssh_user }}
        run: |
          if [ "${{ github.ref }}" == "refs/heads/dev" ]; then
            REMOTE_DIR="~/service/dev"
          elif [ "${{ github.ref }}" == "refs/heads/main" ]; then
            REMOTE_DIR="~/service/main"
          else
            exit 1
          fi
          ssh -p $SSH_PORT $SSH_USER@itisluiz.com <<EOF
            cd $REMOTE_DIR
            git pull
            npm run deploy
          EOF
